development:
  adapter: postgresql
  database: empty_app_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: empty_app_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'].to_s %>
  pool: 15
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'].to_s %>
  password: <%= ENV['DATABASE_PASSWORD'].to_s %>
